# -*- conf -*-

include ~/.config/themes/_generated/kitty.conf

# Font
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size 13
modify_font cell_height 120%

# Window
hide_window_decorations yes
confirm_os_window_close 0

# Keybindings
map F11 toggle_fullscreen

# Zoom in 1.0 steps instead of the default 2.0
map kitty_mod+equal        change_font_size all +1.0
map kitty_mod+plus         change_font_size all +1.0
map kitty_mod+kp_add       change_font_size all +1.0
map kitty_mod+minus        change_font_size all -1.0
map kitty_mod+kp_subtract  change_font_size all -1.0

# Allow remote access
single_instance yes
allow_remote_control yes

# Aesthetics
cursor_shape block
enable_audio_bell no
text_composition_strategy legacy

# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
