pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

QtObject {
  id: root

  readonly property string path: Quickshell.env("HOME") + "/.config/hypr/monitors.lua"

  property var order: []
  property int revision: 0

  function resolveOrder() {
    root.revision
    var known = ({})
    var out = []
    for (var i = 0; i < root.order.length; i++)
      known[root.order[i]] = true
    for (var j = 0; j < root.order.length; j++)
      if (root.findMonitor(root.order[j]))
        out.push(root.order[j])
    var list = Monitors.list
    for (var k = 0; k < list.length; k++)
      if (!known[list[k].name])
        out.push(list[k].name)
    return out
  }

  function findMonitor(name) {
    var list = Monitors.list
    for (var i = 0; i < list.length; i++)
      if (list[i].name === name)
        return list[i]
    return null
  }

  function moveTo(name, index) {
    var current = root.resolveOrder()
    var from = current.indexOf(name)
    if (from < 0 || index < 0 || index >= current.length || from === index)
      return
    current.splice(from, 1)
    current.splice(index, 0, name)
    root.order = current
    root.revision = root.revision + 1
    root.apply()
  }

  function parseMode(text) {
    var m = String(text).match(/^(\d+)x(\d+)@([\d.]+)/)
    if (!m)
      return null
    return { "width": parseInt(m[1]), "height": parseInt(m[2]), "refresh": parseFloat(m[3]) }
  }

  function formatMode(monitor) {
    return monitor.width + "x" + monitor.height + "@" + monitor.refreshRaw.toFixed(2)
  }

  // Hyprland merges monitor rules per output, so `disabled` sticks until it is
  // explicitly cleared; omitting it here leaves the output off forever.
  function buildLines(overrideName, override) {
    var names = root.resolveOrder()
    var x = 0
    var lines = []
    for (var i = 0; i < names.length; i++) {
      var m = root.findMonitor(names[i])
      if (!m)
        continue
      var enabled = !m.disabled
      var scale = m.scale
      var mode = root.formatMode(m)
      var transform = m.transform || 0
      if (names[i] === overrideName && override) {
        if (override.enabled !== undefined)
          enabled = override.enabled
        if (override.scale !== undefined)
          scale = override.scale
        if (override.mode !== undefined)
          mode = override.mode
        if (override.transform !== undefined)
          transform = override.transform
      }
      if (!enabled) {
        lines.push("hl.monitor({ output = \"" + m.name + "\", disabled = true })")
        continue
      }
      var parsed = root.parseMode(mode)
      var logicalWidth = parsed ? Math.round(parsed.width / scale) : Math.round(m.width / scale)
      var bitdepth = String(m.format).indexOf("2101010") >= 0 ? 10 : 8
      lines.push("hl.monitor({ output = \"" + m.name + "\", mode = \"" + mode
        + "\", position = \"" + x + "x0\", scale = " + (Math.round(scale * 10000) / 10000)
        + ", bitdepth = " + bitdepth
        + (transform ? (", transform = " + transform) : "")
        + ", disabled = false })")
      x += logicalWidth
    }
    return lines
  }

  function buildFile(lines) {
    return "------------------\n---- MONITORS ----\n------------------\n\n"
      + "-- Generated by the quickshell display panel. Manual edits are overwritten.\n"
      + "-- See https://wiki.hypr.land/Configuring/Basics/Monitors/\n\n"
      + lines.join("\n") + "\n"
  }

  function evalLines(code) {
    if (String(code).length === 0)
      return
    applyProc.command = ["hyprctl", "eval", code]
    applyProc.running = true
    settleTimer.restart()
  }

  function apply(overrideName, override) {
    var before = root.buildLines().join(" ")
    var lines = root.buildLines(overrideName, override)
    if (lines.length === 0)
      return
    var after = lines.join(" ")
    if (before === after)
      return
    root.evalLines(after)
    file.setText(root.buildFile(lines))
  }

  function setEnabled(name, enabled) {
    var active = 0
    var list = Monitors.list
    for (var i = 0; i < list.length; i++)
      if (!list[i].disabled)
        active++
    if (!enabled && active <= 1)
      return
    root.apply(name, { "enabled": enabled })
  }

  function setScale(name, scale) {
    var m = root.findMonitor(name)
    if (!m)
      return
    root.apply(name, { "scale": Monitors.snapScale(m.width, m.height, scale) })
  }

  function setMode(name, mode) {
    root.apply(name, { "mode": mode })
  }

  function setTransform(name, transform) {
    root.apply(name, { "transform": transform })
  }

  property Timer settleTimer: Timer {
    interval: 300
    onTriggered: Monitors.refresh()
  }

  property Process applyProc: Process {
    onExited: Monitors.refresh()
  }

  property FileView file: FileView {
    path: root.path
    printErrors: false
  }
}
