#!/bin/zsh

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find "${WORKSPACES:-$HOME/Workspaces}" -mindepth 1 -maxdepth 1 -type d | fzf)
fi

[[ -z $selected ]] && return 0

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX && -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected" "$SHELL -i -c '${EDITOR:-nvim} .'"
    return 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected" "$SHELL -i -c '${EDITOR:-nvim} .'"
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t "$selected_name"
else
    tmux switch-client -t "$selected_name"
fi
