display_name: Catppuccin Mocha
wallpaper: wallpaper.jpg

nvim_colorscheme: catppuccin-mocha

scripts:
  - vicinae theme set catppuccin-mocha

colors:
  bg: "#1e1e2e"
  bg_alt: "#181825"
  bg_alt2: "#313244"
  surface: "#45475a"

  fg_dim: "#a6adc8"
  fg: "#cdd6f4"
  fg_alt: "#bac2de"
  fg_bright: "#f5e0dc"

  accent: "#89b4fa"
  accent_alt: "#b4befe"
  accent_fg: "#1e1e2e"
  cursor: "#f5e0dc"

  black: "#45475a"
  red: "#f38ba8"
  green: "#a6e3a1"
  yellow: "#f9e2af"
  blue: "#89b4fa"
  magenta: "#f5c2e7"
  cyan: "#94e2d5"
  white: "#bac2de"
  bright_black: "#585b70"
  bright_red: "#f38ba8"
  bright_green: "#a6e3a1"
  bright_yellow: "#f9e2af"
  bright_blue: "#89b4fa"
  bright_magenta: "#f5c2e7"
  bright_cyan: "#94e2d5"
  bright_white: "#a6adc8"

  success: "#a6e3a1"
  warning: "#f9e2af"
  error: "#f38ba8"
  info: "#94e2d5"
  urgent: "#fab387"
  active: "#a6e3a1"
