#################
### AUTOSTART ###
#################

exec-once = dbus-update-activation-environment --systemd --all

exec-once = hyprpm reload -n # plugins

exec-once = /usr/libexec/hyprpolkitagent

exec-once = ~/.local/bin/hypr-run hyprpaper # wallpaper
exec-once = ~/.local/bin/hypr-run hypridle  # idle management
exec-once = ~/.local/bin/hypr-run swaync    # notifications
exec-once = ~/.local/bin/hypr-run waybar    # top bar

exec-once = wl-paste --type text --watch cliphist store

exec-once = bitwarden              # password manager
exec-once = syncthing --no-browser # sync obsidian

exec-once = systemctl --user restart vicinae.service # menu
exec-once = systemctl --user restart swayosd-server.service # osd
