general {
    lock_cmd = pidof hyprlock || hyprlock      # Screen locker
    before_sleep_cmd = hyprlock                # Lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on # Turn monitors back on after suspend
}

# Turn screen off after 5 minutes of inactivity
listener {
    timeout = 300                                  # 5 minutes
    on-timeout = hyprlock                          # Command to run when timeout is reached
}

# Suspend the system after 10 minutes of inactivity
listener {
    timeout = 600                                  # 10 minutes
    on-timeout = systemctl suspend                 # Command to run when timeout is reached
}
