------------------
---- MONITORS ----
------------------

-- Generated by the quickshell display panel. Manual edits are overwritten.
-- See https://wiki.hypr.land/Configuring/Basics/Monitors/

hl.monitor({ output = "eDP-1", mode = "1920x1200@60.00", position = "0x0", scale = 1.2, bitdepth = 8, disabled = false })
hl.monitor({ output = "HDMI-A-1", mode = "0x0@60.00", position = "1600x0", scale = 1, bitdepth = 8, disabled = false })
